-- Drop tables if they exist to avoid conflicts
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS restaurants;
DROP TABLE IF EXISTS users;

create table restaurants (id bigint generated by default as identity, website varchar(255), address varchar(255) not null, avg_rating float(53) not null, city varchar(255) not null, contact_email varchar(255), contact_phone varchar(255), cuisine varchar(255) not null, description varchar(255), image_url varchar(255) not null, menu varchar(255), name varchar(255) not null, opening_hours varchar(255), pincode varchar(255) not null, price_range float(53) not null, state varchar(255) not null, primary key (id));
create table reviews (id bigint generated by default as identity, rating integer not null, restaurant_id bigint not null, review_content varchar(255) not null, review_topic varchar(255) not null, user_name varchar(255) not null, primary key (id));
create table users (id bigint generated by default as identity, email varchar(255) not null, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, primary key (id));
alter table if exists users drop constraint if exists UK6dotkott2kjsp8vw4d0m25fb7;
alter table if exists users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);


-- Users
INSERT INTO users (email, first_name, last_name, password) VALUES ('john.doe@example.com', 'John', 'Doe', 'pass123');
INSERT INTO users (email, first_name, last_name, password) VALUES ('jane.doe@example.com', 'Jane', 'Doe', 'pass456');
INSERT INTO users (email, first_name, last_name, password) VALUES ('sam.smith@example.com', 'Sam', 'Smith', 'pass789');
INSERT INTO users (email, first_name, last_name, password) VALUES ('alice.jones@example.com', 'Alice', 'Jones', 'pass101');
INSERT INTO users (email, first_name, last_name, password) VALUES ('bob.brown@example.com', 'Bob', 'Brown', 'pass102');
INSERT INTO users (email, first_name, last_name, password) VALUES ('lisa.white@example.com', 'Lisa', 'White', 'pass103');
INSERT INTO users (email, first_name, last_name, password) VALUES ('michael.green@example.com', 'Michael', 'Green', 'pass104');
INSERT INTO users (email, first_name, last_name, password) VALUES ('sarah.hall@example.com', 'Sarah', 'Hall', 'pass105');
INSERT INTO users (email, first_name, last_name, password) VALUES ('karen.johnson@example.com', 'Karen', 'Johnson', 'pass106');
INSERT INTO users (email, first_name, last_name, password) VALUES ('james.lee@example.com', 'James', 'Lee', 'pass107');
INSERT INTO users (email, first_name, last_name, password) VALUES ('gg@gg.com','gg','gg','$2a$10$iBN.dWu7SijTEeWefoG8V.c4MVAmcZiHxBcokTtNv4/sb9n5VAnIC');

-- Restaurants
INSERT INTO restaurants (name, address, city, state, pincode, cuisine, price_range, avg_rating, description, image_url, menu, contact_email, contact_phone, website, opening_hours) VALUES
                                                                                                                                                                         ('Luigis', '123 Main St', 'Santa Clara', 'CA', '95050', 'Italian', 30, 4.5, 'Classic Italian dining with a family-friendly atmosphere.', 'images/luigis.jpg', 'Pizza, Pasta, Risotto', 'contact@luigis.com', '408-555-1234', 'http://luigis.com', 'Mon-Sun 11:00-22:00'),
                                                                                                                                                                         ('Burger Haven', '456 Elm St', 'Tempe', 'AZ', '78940', 'American', 20, 4.0, 'Enjoy our gourmet burgers and crispy fries.', 'images/burgerhaven.jpg', 'Burgers, Fries, Shakes', 'contact@burgerhaven.com', '408-555-5678', 'http://burgerhaven.com', 'Mon-Sun 15:00-22:00'),
                                                                                                                                                                         ('Sushi World', '789 Oak St', 'Santa Clara', 'CA', '62704', 'Japanese', 40, 4.7, 'Fresh sushi and authentic Japanese dishes.', 'images/sushiworld.jpg', 'Sushi, Sashimi, Miso Soup', 'contact@sushiworld.com', '408-555-8765', 'http://sushiworld.com', 'Mon-Sun 10:00-23:00'),
                                                                                                                                                                         ('Green Bowl', '234 Cedar Ln', 'Tempe', 'AZ', '62704', 'Vegetarian', 25, 4.2, 'Delicious and healthy vegetarian and vegan options.', 'images/greenbowl.jpg', 'Salads, Soups, Smoothies', 'contact@greenbowl.com', '408-555-2345', 'http://greenbowl.com', 'Mon-Sun 09:00-24:00'),
                                                                                                                                                                         ('Spice House', '345 Maple Ave', 'Springfield', 'IL', '62704', 'Indian', 22, 4.3, 'Authentic Indian cuisine from all regions of India.', 'images/spicehouse.jpg', 'Curry, Biryani, Naan', 'contact@spicehouse.com', '408-555-5679', 'http://spicehouse.com', 'Mon-Sun 10:00-21:00'),
                                                                                                                                                                         ('BBQ Joint', '567 Pine St', 'Springfield', 'IL', '62704', 'Barbecue', 35, 4.1, 'Smokey ribs and brisket with homemade BBQ sauce.', 'images/bbqjoint.jpg', 'Ribs, Brisket, Pulled Pork', 'contact@bbqjoint.com', '408-555-6781', 'http://bbqjoint.com', 'Mon-Sun 16:00-22:00'),
                                                                                                                                                                         ('Seafood Bay', '678 Spruce St', 'Springfield', 'IL', '62704', 'Seafood', 45, 4.6, 'Fresh seafood dishes from sustainable sources.', 'images/seafoodbay.jpg', 'Oysters, Lobster, Shrimp', 'contact@seafoodbay.com', '408-555-7892', 'http://seafoodbay.com', 'Mon-Sun 11:00-22:00'),
                                                                                                                                                                         ('Steak Corner', '789 Birch Rd', 'Springfield', 'IL', '62704', 'Steakhouse', 50, 4.8, 'Premium steaks grilled to perfection.', 'images/steakcorner.jpg', 'Steaks, Chops, Salads', 'contact@steakcorner.com', '408-555-8903', 'http://steakcorner.com', 'Mon-Sun 11:00-22:00'),
                                                                                                                                                                         ('Pasta Palace', '890 Oak St', 'Springfield', 'IL', '62704', 'Italian', 28, 4.4, 'Homemade pasta with traditional Italian sauces.', 'images/pastapalace.jpg', 'Spaghetti, Ravioli, Gnocchi', 'contact@pastapalace.com', '408-555-9012', 'http://pastapalace.com', 'Mon-Sun 11:00-22:00'),
                                                                                                                                                                         ('Taco Town', '901 Walnut St', 'Springfield', 'IL', '62704', 'Mexican', 18, 4.0, 'Tacos, burritos, and more with authentic Mexican flavors.', 'images/tacotown.jpg', 'Tacos, Burritos, Nachos', 'contact@tacotown.com', '408-555-0123', 'http://tacotown.com', 'Mon-Sun 11:00-22:00');

-- Reviews
INSERT INTO reviews (restaurant_id, user_name, review_topic, review_content, rating) VALUES
                                                                                         (1, 'John Doe', 'Great Experience', 'Loved the ambiance and the pasta was superb.', 5),
                                                                                         (1, 'Jane Doe', 'Good but not great', 'Service was a bit slow but the food was delicious.', 4),
                                                                                         (2, 'Sam Smith', 'Best burgers in town', 'Truly the best burgers Ive ever had!', 5),
(3, 'Alice Jones', 'Delightful Sushi', 'Fresh and tasty sushi. Will come back for more!', 5),
(3, 'Bob Brown', 'Decent but not the best', 'Good sushi, but I have had better.', 3),
(4, 'Lisa White', 'Healthy and tasty', 'Great vegetarian options, loved the smoothies.', 5),
(5, 'Michael Green', 'Spicy and flavorful', 'The curry was fantastic and very authentic.', 5),
(5, 'Sarah Hall', 'Too spicy for me', 'The food was too spicy but the naan bread was good.', 3),
(6, 'Karen Johnson', 'BBQ heaven', 'Best BBQ in town. The ribs fall off the bone!', 5),
(7, 'James Lee', 'Fresh seafood', 'The oysters were very fresh and well-prepared.', 5);


-- Update restaurant ratings based on reviews
UPDATE restaurants SET avg_rating = (SELECT AVG(rating) FROM reviews WHERE restaurant_id = restaurants.id) WHERE id IN (SELECT DISTINCT restaurant_id FROM reviews);
