-- Dropping existing tables
drop table if exists reviews cascade;
drop table if exists restaurants cascade;
drop table if exists users cascade;

-- Creating tables
create table restaurants (
                             price_range float(53),
                             id bigint generated by default as identity,
                             address varchar(255) not null,
                             contact_info varchar(255),
                             cuisine varchar(255),
                             image_url varchar(255),
                             menu varchar(255),
                             name varchar(255) not null,
                             opening_hours varchar(255),
                             primary key (id)
);

create table users (
                       id bigint generated by default as identity,
                       email varchar(255) not null unique,
                       first_name varchar(255) not null,
                       last_name varchar(255) not null,
                       password varchar(255) not null,
                       primary key (id)
);

create table reviews (
                         id bigint generated by default as identity,
                         rating integer not null,
                         text varchar(255),
                         restaurant_id bigint not null,
                         user_name varchar(255) not null,
                         primary key (id)
);

-- Adding foreign key constraints to reviews table
alter table reviews
    add constraint FKsu8ow2q842enesfbqphjrfi5g
        foreign key (restaurant_id) references restaurants;

-- Inserting sample data into restaurants table
INSERT INTO restaurants (price_range, address, contact_info, cuisine, image_url, menu, name, opening_hours) VALUES
    (2.0, '123 Main St, Springfield', '555-1234', 'Italian', 'luigis.jpg', 'menu1.pdf', 'Luigis', 'Mon-Sun 11:00-22:00'),
(1.0, '456 Elm St, Springfield', '555-5678', 'Fast Food', 'burgerhaven.jpg', 'menu2.pdf', 'Burger Haven', 'Mon-Sun 10:00-23:00'),
(3.0, '789 Oak St, Springfield', '555-8765', 'Sushi', 'sushiworld.jpg', 'menu3.pdf', 'Sushi World', 'Mon-Sun 12:00-21:00');

-- Inserting sample data into users table
INSERT INTO users (email, first_name, last_name, password) VALUES
('john.doe@example.com', 'John', 'Doe', 'password123'),
('jane.smith@example.com', 'Jane', 'Smith', 'password456'),
('admin@example.com', 'Admin', 'User', 'adminpassword');

-- Inserting sample data into reviews table
INSERT INTO reviews (rating, restaurant_id, text, user_name) VALUES
(5, 1, 'Amazing food and great service!', 'john.doe@example.com'),
(4, 2, 'Good burgers but the fries were a bit salty.', 'jane.smith@example.com'),
(3, 3, 'Sushi was fresh but the wait time was long.', 'admin@example.com');
