-- Drop tables if they exist to avoid conflicts
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS restaurants;
DROP TABLE IF EXISTS users;

create table restaurants (id bigint generated by default as identity, address varchar(255) not null, avg_rating float(53) not null, city varchar(255) not null, contact_email varchar(255), contact_phone varchar(255), cuisine varchar(255) not null, description varchar(255), image_url varchar(255) not null, menu varchar(255), name varchar(255) not null, opening_hours varchar(255), pincode varchar(255) not null, price_range float(53) not null, state varchar(255) not null, primary key (id));
create table reviews (id bigint generated by default as identity, rating integer not null, restaurant_id bigint not null, review_content varchar(255) not null, review_topic varchar(255) not null, user_name varchar(255) not null, primary key (id));
create table users (id bigint generated by default as identity, email varchar(255) not null, first_name varchar(255) not null, last_name varchar(255) not null, password varchar(255) not null, primary key (id));
alter table if exists users drop constraint if exists UK6dotkott2kjsp8vw4d0m25fb7;
alter table if exists users add constraint UK6dotkott2kjsp8vw4d0m25fb7 unique (email);

INSERT INTO restaurants (name, address, city, state, pincode, cuisine, price_range, avg_rating, contact_email, contact_phone, opening_hours, menu, image_url, description) VALUES
                                                                                                                                                                               ('Luigis', '123 Main St', 'Springfield', 'IL', '12345', 'Italian', 2.0, 5.0, 'contact@luigis.com', '555-1234', 'Mon-Sun 11:00-22:00', 'Pizza, Pasta, Risotto', 'https://source.unsplash.com/1600x900/?italian-restaurant', 'Classic Italian dining with a family-friendly atmosphere.'),                                                                                                                                                                      ('Burger Haven', '456 Elm St', 'Springfield', 'IL', '12345', 'Fast Food', 1.0, 4.0, 'contact@burgerhaven.com', '555-5678', 'Mon-Sun 10:00-23:00', 'Burgers, Fries, Shakes', 'https://source.unsplash.com/1600x900/?burger-restaurant', 'Enjoy our gourmet burgers and crispy fries.'),
                                                                                                                                                                               ('Sushi World', '789 Oak St', 'Springfield', 'IL', '12345', 'Sushi', 3.0, 3.0, 'contact@sushiworld.com', '555-8765', 'Mon-Sun 12:00-21:00', 'Sushi, Sashimi, Miso Soup', 'https://source.unsplash.com/1600x900/?sushi-restaurant', 'Fresh sushi and authentic Japanese dishes.');
INSERT INTO reviews (restaurant_id, user_name, rating, review_content, review_topic) VALUES
                                                                                         (1, 'John Doe', 5, 'Amazing food and great service!', 'Excellent!'),
                                                                                         (1, 'Jane Smith', 4, 'Great pasta but long wait times.', 'Very Good'),
                                                                                         (2, 'Alice Johnson', 3, 'Burgers are good but not the best in town.', 'Average'),
                                                                                         (3, 'Bob Brown', 2, 'Sushi was not fresh, quite disappointing.', 'Below Average');

INSERT INTO users (email, first_name, last_name, password) VALUES
                                                               ('john.doe@example.com', 'John', 'Doe', 'hashed_password1'),
                                                               ('jane.smith@example.com', 'Jane', 'Smith', 'hashed_password2'),
                                                               ('alice.johnson@example.com', 'Alice', 'Johnson', 'hashed_password3'),
                                                               ('gg@gg.com','gg','gg','$2a$10$iBN.dWu7SijTEeWefoG8V.c4MVAmcZiHxBcokTtNv4/sb9n5VAnIC');

